#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Payment industry standard translations
translations = {
    # HTML attributes
    'lang="zh-CN"': 'lang="en"',
    '商户后台管理系统': 'Merchant Management System',
    
    # Header
    'MP商户后台': 'MP Merchant Portal',
    'Merchant Platform': 'Merchant Platform',
    
    # Main Menu
    '首页概览': 'Dashboard',
    '我的资产': 'My Assets',
    '资产余额': 'Account Balance',
    '账户流水': 'Transaction History',
    '收款入金': 'Receive Funds',
    '收法币': 'Receive Fiat',
    '收数币': 'Receive Crypto',
    '换汇中心': 'Exchange Center',
    '法币换汇': 'Fiat Exchange',
    '数法承兑': 'Crypto to Fiat',
    '付款提币': 'Payment & Withdrawal',
    '付数币': 'Withdraw Crypto',
    '付法币': 'Pay Fiat',
    '收款人管理': 'Payee Management',
    '数币地址': 'Crypto Addresses',
    '法币收款人': 'Fiat Payees',
    
    # Dashboard
    '总资产': 'Total Assets',
    '总余额': 'Total Balance',
    '数币资产': 'Crypto Assets',
    '法币余额': 'Fiat Balance',
    '本月交易': 'Monthly Transactions',
    '较上月': 'vs last month',
    '快捷操作': 'Quick Actions',
    '最近交易': 'Recent Transactions',
    '查看全部': 'View All',
    '日期': 'Date',
    '类型': 'Type',
    '金额': 'Amount',
    '状态': 'Status',
    '已完成': 'Completed',
    '处理中': 'Processing',
    '失败': 'Failed',
    '待审核': 'Pending Review',
    
    # Balance Page
    '总资产（美元等值）': 'Total Assets (USD Equivalent)',
    '截至': 'As of',
    '法币余额': 'Fiat Currency Balance',
    '管理币种': 'Manage Currencies',
    '数字货币余额': 'Cryptocurrency Balance',
    '美元': 'US Dollar',
    '欧元': 'Euro',
    '英镑': 'British Pound',
    '人民币': 'Chinese Yuan',
    '港币': 'Hong Kong Dollar',
    '日元': 'Japanese Yen',
    
    # Transaction History
    '筛选': 'Filters',
    '时间范围': 'Time Period',
    '今天': 'Today',
    '最近7天': 'Last 7 Days',
    '最近30天': 'Last 30 Days',
    '自定义': 'Custom',
    '交易类型': 'Transaction Type',
    '全部类型': 'All Types',
    '充值': 'Deposit',
    '提现': 'Withdrawal',
    '兑换': 'Exchange',
    '支付': 'Payment',
    '币种': 'Currency',
    '全部币种': 'All Currencies',
    '搜索': 'Search',
    '交易记录': 'Transaction Records',
    '导出': 'Export',
    '交易ID': 'Transaction ID',
    '日期时间': 'Date & Time',
    '手续费': 'Fee',
    '操作': 'Actions',
    '详情': 'Details',
    '数币充值': 'Crypto Deposit',
    '法币支付': 'Fiat Payment',
    
    # Receive Crypto
    '收款地址': 'Receiving Address',
    '选择网络': 'Select Network',
    '选择币种': 'Select Currency',
    '收款二维码': 'Receiving QR Code',
    '请先选择网络和币种': 'Please select network and currency first',
    '收款地址：': 'Receiving Address:',
    '复制地址': 'Copy Address',
    '地址已复制': 'Address copied',
    '重要提示': 'Important Notice',
    '请确认': 'Please confirm',
    '网络选择': 'network selection',
    '发送到错误的网络可能导致资产损失': 'Sending to wrong network may result in asset loss',
    '最小充值金额': 'Minimum deposit amount',
    '小于最小金额的充值将不会到账': 'Deposits below minimum amount will not be credited',
    '充值到账时间': 'Deposit arrival time',
    '需要': 'Requires',
    '个网络确认': 'network confirmations',
    '支持': 'Support',
    '如需帮助，请登录邮箱生成工单': 'For assistance, please create a ticket via email',
    '或通过': 'or contact us via',
    '联系我们': 'contact us',
    
    # Receive Fiat
    '收款账号': 'Receiving Accounts',
    '添加收款账号': 'Add Receiving Account',
    '下列所需填写信息的详细步骤请': 'For detailed steps on filling required information, please',
    '点击查看操作指南': 'click to view operation guide',
    '全部': 'All',
    '全球收款账号': 'Global Receiving Accounts',
    '本地收款账号': 'Local Receiving Accounts',
    '处理中': 'Processing',
    '激活失败': 'Activation Failed',
    '本地收款账户': 'Local Receiving Account',
    '全球收款账户': 'Global Receiving Account',
    '货物贸易收款': 'Trade Payment Collection',
    '隐藏': 'Hide',
    '使用说明': 'Usage Instructions',
    '全球收款账户信息仅用于非中国收款取货物贸易项下海外买家支付的货款': 'Global receiving account information is only for collecting trade payments from overseas buyers outside China',
    '本地收款账户信息仅用于非中国收款取货物贸易项下卖家支付的货款': 'Local receiving account information is only for collecting trade payments from sellers outside China',
    '禁止从': 'Prohibited from receiving payments from',
    '等国家或地区收款': 'and other countries or regions',
    '点击查看': 'Click to view',
    '限制禁收国家列表': 'Restricted Countries List',
    '银行及我司有权对该账户欧外汇进行审核': 'Banks and our company reserve the right to review foreign exchange transactions',
    '收款人有义务配合提供相关证明资金来源': 'Payee is obligated to provide proof of fund source',
    '如无法通过则可禁止提现': 'Withdrawal may be prohibited if verification fails',
    '如有异常，我司有权拒绝提现': 'We reserve the right to refuse withdrawal if abnormalities are detected',
    '如由卖家以外的第三方付款': 'If payment is made by a third party other than the seller',
    '请和卖家认真核实收款人和卖家的关系': 'please verify the relationship between payee and seller',
    '并提醒收款人在汇款附言中注明': 'and remind the payee to note in the remittance message',
    '附言需包含收款人和卖家关系及发票编号': 'message should include payee-seller relationship and invoice number',
    
    # Account Detail Modal
    '账户详情': 'Account Details',
    '关闭': 'Close',
    '一键复制': 'Copy All',
    '支持美国境内收款': 'Supports domestic US payments',
    '收款限额为单日': 'Daily receiving limit',
    '每年': 'Annual limit',
    '基础信息': 'Basic Information',
    '账户名称': 'Account Name',
    '账户类型': 'Account Type',
    '账户用途': 'Account Purpose',
    '账户状态': 'Account Status',
    '正常': 'Active',
    '创建时间': 'Created At',
    '外贸收款': 'Trade Payment',
    '银行号信息': 'Bank Information',
    '账户币种': 'Account Currency',
    '账户所在国家/地区': 'Account Country/Region',
    '银行名称': 'Bank Name',
    '银行账号': 'Bank Account Number',
    '银行地址': 'Bank Address',
    '银行所在邮编': 'Bank Postal Code',
    '城市': 'City',
    
    # Add Receive Account Modal
    '添加外贸收款账号': 'Add Trade Receiving Account',
    '美金账户': 'USD Account',
    '欧元账户': 'EUR Account',
    '英镑账户': 'GBP Account',
    '印尼账户': 'IDR Account',
    '新加坡账户': 'SGD Account',
    '港币账户': 'HKD Account',
    '澳元账户': 'AUD Account',
    '加元账户': 'CAD Account',
    '日元账户': 'JPY Account',
    '离岸人民币账户': 'CNH Account',
    '中国香港-全球收款账户': 'Hong Kong - Global Receiving Account',
    '华侨银行(香港)有限公司': 'OCBC Bank (Hong Kong) Limited',
    '美国-全球收款账户': 'USA - Global Receiving Account',
    '多币种': 'Multi-Currency',
    '不支持ATM': 'ATM not supported',
    '不支持签票': 'Check not supported',
    '不支持网银登录': 'Online banking login not supported',
    '收款账户名称': 'Receiving Account Name',
    '账户名称必须与您提供的证件的英文名称': 'Account name must match the English name on your provided documents',
    '有任何差异或有人姓名不全情况': 'If there are any discrepancies or incomplete names',
    '如有任何问题，请联系您的客户经理': 'Please contact your account manager if you have any questions',
    '支持收款币种': 'Supported Currencies',
    '买家付款地区': 'Buyer Payment Region',
    '全球': 'Global',
    '非制裁地区': 'Non-sanctioned Regions',
    '支持收款方式': 'Supported Payment Methods',
    '和中国香港': 'and Hong Kong',
    '收款': 'Payment Collection',
    '和美国': 'and USA',
    '核心开通时效': 'Activation Time',
    '实时开通': 'Instant Activation',
    '添加': 'Add',
    '温馨提示': 'Important Notice',
    '禁止接受来自': 'Prohibited from accepting payments from',
    '伊朗、叙利亚、白俄罗斯、朝鲜、俄罗斯、古巴、克里米亚、缅甸、委内瑞拉、乌克兰、顿涅茨克、卢甘斯克、赫尔松、扎波罗热、阿拉伯联合酋长国、吉尔吉斯斯坦': 'Iran, Syria, Belarus, North Korea, Russia, Cuba, Crimea, Myanmar, Venezuela, Ukraine, Donetsk, Luhansk, Kherson, Zaporizhzhia, UAE, Kyrgyzstan',
    '等国家或地区收汇': 'and other countries or regions',
    '更多禁收国家信息，请参考禁收国家说明': 'For more information on restricted countries, please refer to the restricted countries list',
    '如果该账号接收到上述国家或地区的款项，可能导致账号关闭': 'If this account receives payments from the above countries or regions, the account may be closed',
    '银行及我司有权对该账户敏感外汇交易进行审核': 'Banks and our company reserve the right to review sensitive foreign exchange transactions',
    '收款人有义务配合提供资料以证明资金来源': 'Payee is obligated to provide documentation to prove the source of funds',
    '如审核通过则可正常提现': 'If verification passes, withdrawal can proceed normally',
    '如由卖家以外的第三方付款，请和买家确认付款人和买家的关系': 'If payment is made by a third party other than the seller, please confirm the relationship between the payer and buyer',
    '并提醒付款人在汇款时添加附言': 'and remind the payer to add a message when remitting',
    '附言需备注付款人和买家关系及invoice number': 'The message should note the payer-buyer relationship and invoice number',
    '取消': 'Cancel',
    '确认添加': 'Confirm Add',
    '请选择一个收款账户': 'Please select a receiving account',
    '收款账号添加成功': 'Receiving account added successfully',
    
    # Withdraw Crypto
    '提币': 'Withdraw',
    '可用余额': 'Available Balance',
    '选择币种': 'Select Currency',
    '选择网络': 'Select Network',
    '提币地址': 'Withdrawal Address',
    '请选择提币地址': 'Please select withdrawal address',
    '提币数量': 'Withdrawal Amount',
    '请输入提币数量': 'Please enter withdrawal amount',
    '全部': 'All',
    '交易详情': 'Transaction Details',
    '提币数量：': 'Withdrawal Amount:',
    '网络手续费：': 'Network Fee:',
    '预计到账：': 'Estimated Receipt:',
    '提交提币': 'Submit Withdrawal',
    '请选择币种': 'Please select currency',
    '请选择网络': 'Please select network',
    '请选择提币地址': 'Please select withdrawal address',
    '请输入提币数量': 'Please enter withdrawal amount',
    '提币申请已提交': 'Withdrawal request submitted',
    
    # Pay Fiat
    '付款信息': 'Payment Information',
    '选择收款人': 'Select Payee',
    '请选择收款人': 'Please select payee',
    '付款金额': 'Payment Amount',
    '请输入付款金额': 'Please enter payment amount',
    '付款币种': 'Payment Currency',
    '费用明细': 'Fee Details',
    '付款金额：': 'Payment Amount:',
    '手续费：': 'Transaction Fee:',
    '预计收款：': 'Estimated Receipt:',
    '附加信息': 'Additional Information',
    '付款日期': 'Payment Date',
    '付款用途': 'Payment Purpose',
    '请输入付款用途': 'Please enter payment purpose',
    '提交付款': 'Submit Payment',
    '付款信息已提交，进入下一步确认': 'Payment information submitted, proceed to confirmation',
    
    # Crypto Addresses
    '地址列表': 'Address List',
    '新增地址': 'Add Address',
    '地址别名': 'Address Alias',
    '网络': 'Network',
    '地址': 'Address',
    '编辑': 'Edit',
    '删除': 'Delete',
    '新增地址': 'Add Address',
    '请选择网络': 'Please select network',
    '请选择币种': 'Please select currency',
    '提币地址': 'Withdrawal Address',
    '请输入提币地址': 'Please enter withdrawal address',
    '地址别名': 'Address Alias',
    '请输入地址别名': 'Please enter address alias',
    '确定': 'Confirm',
    '请选择网络': 'Please select network',
    '请选择币种': 'Please select currency',
    '请输入地址': 'Please enter address',
    '请输入别名': 'Please enter alias',
    '地址已保存': 'Address saved',
    
    # Fiat Payees
    '收款人列表': 'Payee List',
    '新增': 'Add New',
    '快速检索银行账户名称': 'Quick search by bank account name',
    '银行账户名称': 'Bank Account Name',
    '银行账户所在地': 'Bank Account Location',
    '收款人类型': 'Payee Type',
    '账户币种': 'Account Currency',
    '说明': 'Description',
    '支付方式': 'Payment Method',
    '银行': 'Bank',
    '查看': 'View',
    '补充材料': 'Supplement Materials',
    '个人': 'Individual',
    '企业': 'Corporate',
    '中国': 'China',
    '越南': 'Vietnam',
    '中国企业': 'China Corporate',
    '待补充': 'Pending Supplement',
    '审核拒绝': 'Rejected',
    '审核通过': 'Approved',
    '新增收款账户': 'Add Receiving Account',
    '请选择您的收款人': 'Please select your payee',
    '请选择': 'Please select',
    '新的收款人': 'New Payee',
    '您将添加全新的收款人以及其账户信息': 'You will add a new payee and their account information',
    '其他服务商': 'Other Service Provider',
    '其他收款人': 'Other Payee',
    '基本信息': 'Basic Information',
    '收款人类型': 'Payee Type',
    '企业': 'Corporate',
    '个人': 'Individual',
    '收款人分类': 'Payee Category',
    '其他服务商': 'Other Service Provider',
    '其他收款人': 'Other Payee',
    '员工': 'Employee',
    '银行账户信息': 'Bank Account Information',
    '账户邮称': 'Account Alias',
    '请您设置一个邮称以便您可以快速检索': 'Please set an alias for quick search',
    '银行账户所在地': 'Bank Account Location',
    '中国-CN': 'China-CN',
    '美国-US': 'USA-US',
    '英国-UK': 'UK-UK',
    '账户币种': 'Account Currency',
    '港元-HKD': 'HKD-Hong Kong Dollar',
    '人民币-CNY': 'CNY-Chinese Yuan',
    '美元-USD': 'USD-US Dollar',
    '支付方式': 'Payment Method',
    '通过SWIFT电汇网络的转账方式': 'Transfer via SWIFT wire network',
    '可支持大额转账和较长的交易周期': 'Supports large transfers and longer transaction cycles',
    '需提供SWIFT号和银行代码': 'Requires SWIFT code and bank code',
    '所示费用与': 'Fees shown are based on',
    '收费模式': 'fee structure',
    '即收款人承担中间费用': 'meaning payee bears intermediary fees',
    '个工作日': 'business days',
    '账户名称': 'Account Name',
    '请您输入人员的账户名称': 'Please enter the account name',
    '收款人银行账号': 'Payee Bank Account Number',
    '请输入收款人银行账号': 'Please enter payee bank account number',
    '银行名称': 'Bank Name',
    '请填写银行名称，高标可能造成付款失败': 'Please enter bank name, errors may cause payment failure',
    '请输入SWIFT CODE': 'Please enter SWIFT CODE',
    '联系人信息': 'Contact Information',
    '收款人地址': 'Payee Address',
    '请选择国家/地区': 'Please select country/region',
    '请选择省/州': 'Please select state/province',
    '城市': 'City',
    '请输入具体地址': 'Please enter detailed address',
    '为了保证您能及时收款成功': 'To ensure successful and timely payment receipt',
    '我们可能会自动去除当前银行不支持的特殊符号': 'we may automatically remove special characters not supported by the bank',
    '该操作不会影响您的正常付款': 'This will not affect your normal payments',
    '提交': 'Submit',
    '收款人信息已提交审核': 'Payee information submitted for review',
    
    # Fiat Exchange
    '法币换汇': 'Fiat Exchange',
    '您可以选择卖出币种和买入币种': 'You can select the currency to sell and the currency to buy',
    '并输入对应金额实时换汇': 'and enter the amount for real-time exchange',
    '您将实时收到买入金额': 'You will receive the purchased amount in real-time',
    '创建实时换汇交易': 'Create Real-Time Exchange Transaction',
    '卖出': 'Sell',
    '请输入金额': 'Please enter amount',
    '最低': 'Minimum',
    '最高': 'Maximum',
    '全部卖出': 'Sell All',
    '可用余额': 'Available Balance',
    '设置扣款顺序': 'Set Deduction Order',
    '参考汇率': 'Reference Rate',
    '买入': 'Buy',
    '您可以输入金额': 'You can enter amount',
    '查询汇率': 'Query Rate',
    '汇率': 'Exchange Rate',
    '卖出金额': 'Sell Amount',
    '买入金额': 'Buy Amount',
    '汇率有效期': 'Rate Validity Period',
    '确认换汇': 'Confirm Exchange',
    '汇率时效': 'Rate Validity',
    '查询到的汇率有效期为30秒': 'Queried rate is valid for 30 seconds',
    '请在有效期内完成换汇操作': 'Please complete exchange within validity period',
    '金额限制': 'Amount Limit',
    '单笔换汇最低': 'Minimum per transaction',
    '到账时间': 'Arrival Time',
    '换汇成功后，资金将实时到账': 'Funds will arrive in real-time after successful exchange',
    '请输入有效金额（最低10）': 'Please enter valid amount (minimum 10)',
    '金额超过最大限制（最高3000000）': 'Amount exceeds maximum limit (maximum 3000000)',
    '汇率已过期，请重新查询': 'Rate expired, please query again',
    '确认换汇？': 'Confirm exchange?',
    '换汇成功！资金已实时到账。': 'Exchange successful! Funds arrived in real-time.',
    
    # Crypto to Fiat
    '承兑': 'Exchange',
    '余额': 'Balance',
    '最大': 'Max',
    '兑换': 'Exchange',
    '兑换直率': 'Exchange Rate',
    '兑换直率为真实兑换的市场价格': 'Exchange rate is the actual market price',
    '僅供參考': 'For reference only',
    '以交易執行時的實際匯率為準': 'Actual rate at execution time shall prevail',
    '兑换手續費': 'Exchange Fee',
    '請確認兌換手續費': 'Please confirm exchange fee',
    '如有任何手續費問題': 'If you have any questions about fees',
    '請先與您的客戶經理確認': 'please confirm with your account manager first',
    '最近兑换': 'Recent Exchanges',
    '分钟前': 'minutes ago',
    '小时前': 'hours ago',
    '获得': 'Received',
    '实时兑换率': 'Real-Time Exchange Rates',
    '数币': 'Crypto',
    '法币': 'Fiat',
    '兑换率': 'Exchange Rate',
    '手续费': 'Fee',
    '更新时间': 'Updated',
    '刚刚': 'Just now',
    '确认兑换？': 'Confirm exchange?',
    '兑换成功！资金已实时到账。': 'Exchange successful! Funds arrived in real-time.',
    '请输入卖出金额': 'Please enter sell amount',
    '请输入买入金额': 'Please enter buy amount',
    
    # Common Terms
    '项': 'items',
    '每页': 'Per page',
    '上一页': 'Previous',
    '下一页': 'Next',
    '前往': 'Go to',
    '页': 'page',
    '共': 'Total',
}

# Read the source file
with open('merchant-dashboard.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Apply translations
for chinese, english in translations.items():
    content = content.replace(chinese, english)

# Write the translated file
with open('merchant-dashboard-en.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation completed successfully!")
print(f"Total translations applied: {len(translations)}")
